### ISSUE TITLE
[DEMO] Definition Features

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-laravel#2]

**Comment by yaegassy** [comment]
## View definition

> from PHP to Blade

https://github.com/yaegassy/coc-laravel/assets/188642/8cf4f009-c874-4691-ac68-26f758bb487b

**Comment by yaegassy** [comment]
## Blade View definition

> from Blade to Blade

https://github.com/yaegassy/coc-laravel/assets/188642/77be4261-0b07-47c4-875b-d7c59dbe8897

**Comment by yaegassy** [comment]
## Component definition

> from Blade -> PHP or Blade

https://github.com/yaegassy/coc-laravel/assets/188642/58fe3725-952d-4cad-94da-6da2acf47110

**Comment by yaegassy** [comment]
## Livewire directive definition

https://github.com/yaegassy/coc-laravel/assets/188642/7b74da27-5b66-4bf3-815d-670b53592ae5

**Comment by villeneuve-michael** [comment]
Hey quick question, I'm trying to jump to a blade definition using C-] but it's not working. Is there any specific shortcut or my problem is most likely with the install?
